#!/bin/sh

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=EVAL_BEAST
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=2:00:00
#SBATCH --output=outputs/EVAL%A.out
#SBATCH --error=outputs/EVAL%A.err

module purge
module load 2022
module load Anaconda3/2022.05
source activate nmt
python3 scripts/evaluate_test.py --checkpoint_path results/checkpoints/high_lr_finetune_test